deployment:
  backend:
    replicaCount: 1
    image:
      repository: ankur512512/python-fastapi-userlogin
      pullPolicy: IfNotPresent
      tag: 1457cb6ee5e584e7d6555af8b2fb9495c9325e56
    imagePullSecrets: []
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    nodeSelector: {}
    tolerations: []
    affinity: {}
nameOverride: ''
fullnameOverride: pythonwebapp
serviceAccount:
  create: true
  annotations: {}
  name: ''
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: akpythonauth.webhop.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: akpythonauth-webhop-me
      hosts:
        - akpythonauth.webhop.me
