deployment:
  backend:
    replicaCount: 1
    image:
      repository: ankur512512/python-fastapi-backend
      pullPolicy: Always
      tag: latest
    imagePullSecrets: []
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    nodeSelector: {}
    tolerations: []
    affinity: {}
  db:
    replicaCount: 1
    image:
      repository: bitnami/postgresql
      pullPolicy: IfNotPresent
      tag: 17.2.0
    imagePullSecrets: []
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    nodeSelector: {}
    tolerations: []
    affinity: {}
  frontend:
    replicaCount: 1
    image:
      repository: ankur512512/python-fastapi-frontend
      pullPolicy: Always
      tag: latest
    imagePullSecrets: []
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources: {}
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    nodeSelector: {}
    tolerations: []
    affinity: {}
nameOverride: ''
fullnameOverride: pythonwebapp
serviceAccount:
  create: true
  annotations: {}
  name: ''
service:
  backend:
    type: ClusterIP
    port: 8080
  db:
    type: ClusterIP
    port: 5432
  frontend:
    type: ClusterIP
    port: 5173

ingress:
  enabled: true
  hosts:
    host: akpythonauth.webhop.me
  ingressClassName: nginx
  annotations:
  tls:
    enabled: true
    secretName: akpythonauth-webhop-me
