apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ include "argocd-python-userlogin.fullname" . }}
  labels:
    {{- include "argocd-python-userlogin.labels" . | nindent 4 }}
    app: frontend
spec:
  {{- if not .Values.deployment.frontend.autoscaling.enabled }}
  replicas: {{ .Values.deployment.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "argocd-python-userlogin.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      {{- with .Values.deployment.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argocd-python-userlogin.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      {{- with .Values.deployment.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "argocd-python-userlogin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.frontend.image.repository }}:{{ .Values.deployment.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.frontend.image.pullPolicy }}
          env:
          - name: VITE_BACKEND_URL
            value: /api
          ports:
            - name: http
              containerPort: 5173
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.deployment.frontend.resources | nindent 12 }}
      {{- with .Values.deployment.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
